name: new_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.7

  # Navigation
  go_router: ^13.0.0

  # Network
  dio: ^5.4.0

  # Auth
  google_sign_in: ^6.2.1

  # OTP input
  pinput: ^6.0.2

  # Local Storage
  shared_preferences: ^2.2.2

  # Font
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true