name: new_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^9.2.1

  # Navigation
  go_router: ^17.2.3

  # Network
  dio: ^5.4.0
  json_annotation: ^4.9.0

  # Auth
  google_sign_in: ^7.2.0

  # OTP input
  pinput: ^5.0.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Font
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
flutter:
  uses-material-design: true